### ISSUE TITLE
where fantasy-land/laws/* are  located?

### ISSUE THREAD

**Issue by safareli** [fantasyland/fantasy-check#10]
I could not find where laws folder is located but it's actually used in tests(test/law.js) and in other fantasy modules

**Comment by adicirstei** [comment]
Removed several commits back. I don't know what replaced them.

to look at the last version you can look at the [commit](https://github.com/fantasyland/fantasy-check/tree/c36c96cf6be463749edc9fb80ce343a41d4105aa) before the cleanup (5125ca29c075a5856331f687d83b8be68b148ebf).

[LATER EDIT]

It seems the commit comment point us to [the main repo](https://github.com/fantasyland/fantasy-land/tree/master/laws). 

> - Removed conforms
> - Removed all the laws!
>   - These can all be found in `fantasy-land` main repo. These will
>     always be more up to date than the ones in this library.
> - Cleaned up various errors and bugs

**Comment by SimonRichardson** [comment]
I removed them, because people requested them elsewhere, so rather than duplicated code, just have it where it's more visible and accessible

**Comment by safareli** [comment]
I did not knew that it was in fantasy-land, Thanks!
