### ISSUE TITLE
Using jsverify

### ISSUE THREAD

**Issue by gilligan** [fantasyland/fantasy-check#9]
Is there any specific reason not to use https://github.com/jsverify/jsverify for this?

**Comment by SimonRichardson** [comment]
Because fantasy check was out way, way, way before

**Comment by SimonRichardson** [comment]
https://github.com/puffnfresh/bilby.js/blob/master/src/check.js see original version

**Comment by gilligan** [comment]
@SimonRichardson alright. I did not check that. I suppose switching to jsverify might make sense in the same way that switching from nodeunit to mocha might be a good idea. Of course neither is a defect.

I was just wondering. Thanks for your swift response.

**Comment by SimonRichardson** [comment]
If you want to change then we should change all the repos for consistency.

**Comment by gilligan** [comment]
Yes, you said that. I think the all or nothing approach means it will always stay the way it is. But I am only an otusider to this as I already pointed out.

Thanks.
